options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/$PROJECT_ID/locations/europe-west1/workerPools/knada-cloudbuild-pool'

steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s
  - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/knorten/knorten:20cd3f7
  - --location=$_REGION
  - --cluster=$_CLUSTER
images:
- "europe-west1-docker.pkg.dev/$PROJECT_ID/knorten/knorten:20cd3f7"
