options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/knorten/knorten:$SHORT_SHA-$(date +%m-%d-%Y)', '.' ]
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/knorten/knorten:$SHORT_SHA-$(date +%m-%d-%Y)'
