apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knorten
  namespace: knada-system
spec:
  secretName: knorten-certificate
  dnsNames:
    - knorten.knada.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
    group: cert-manager.io
