apiVersion: apps/v1
kind: Deployment
metadata:
  name: knorten
  namespace: knada-system
  labels:
    app: knorten
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knorten
  template:
    metadata:
      labels:
        app: knorten
    spec:
      serviceAccountName: knorten
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: knorten
        image: europe-west1-docker.pkg.dev/knada-gcp/knorten/knorten
        ports:
        - containerPort: 8080
        env:
          - name: "HOSTNAME"
            value: "knorten.knada.io"
          - name: "KNELM_IMAGE"
            value: europe-west1-docker.pkg.dev/knada-gcp/knorten/knelm:v8
        envFrom:
        - secretRef:
            name: knorten
      - name: cloudsql-proxy
        command:
        - /cloud_sql_proxy
        - -term_timeout=30s
        - -instances=knada-gcp:europe-west1:knorten=tcp:5432
        image: gcr.io/cloudsql-docker/gce-proxy:1.29.0-alpine
        ports:
        - containerPort: 5432
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 2
          runAsNonRoot: true
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
