apiVersion: apps/v1
kind: Deployment
metadata:
  name: knorten-test
  namespace: knada-system
  labels:
    app: knorten-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knorten-test
  template:
    metadata:
      labels:
        app: knorten-test
    spec:
      containers:
      - name: knorten
        image: ""
        ports:
        - containerPort: 8080
