proxy:
  secretToken: {{ .ProxyToken }}
  service:
    type: ClusterIP

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

singleuser:
  image:
    name: {{ .ImageName }}
    tag: {{ .ImageTag }}
